// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"
	models "wordsGo/internal/repository/modelsDB"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockUserRepository) Create(ctx context.Context, req *models.UserDB) (*models.UserDB, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.UserDB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserDB) (*models.UserDB, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserDB) *models.UserDB); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserDB) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *modelsDB.UserDB
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, req interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, req *models.UserDB)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserDB))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 *models.UserDB, _a1 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *models.UserDB) (*models.UserDB, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(_a0 error) *MockUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasswordHashByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) GetPasswordHashByEmail(ctx context.Context, email string) (*models.UserDB, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordHashByEmail")
	}

	var r0 *models.UserDB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.UserDB, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserDB); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetPasswordHashByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordHashByEmail'
type MockUserRepository_GetPasswordHashByEmail_Call struct {
	*mock.Call
}

// GetPasswordHashByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetPasswordHashByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetPasswordHashByEmail_Call {
	return &MockUserRepository_GetPasswordHashByEmail_Call{Call: _e.mock.On("GetPasswordHashByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetPasswordHashByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetPasswordHashByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetPasswordHashByEmail_Call) Return(_a0 *models.UserDB, _a1 error) *MockUserRepository_GetPasswordHashByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetPasswordHashByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.UserDB, error)) *MockUserRepository_GetPasswordHashByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*models.UserDB, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.UserDB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.UserDB, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.UserDB); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(_a0 *models.UserDB, _a1 error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.UserDB, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx, order, pagination
func (_m *MockUserRepository) GetUsers(ctx context.Context, order string, pagination models.Pagination) ([]models.UserDB, uint64, error) {
	ret := _m.Called(ctx, order, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []models.UserDB
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Pagination) ([]models.UserDB, uint64, error)); ok {
		return rf(ctx, order, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Pagination) []models.UserDB); ok {
		r0 = rf(ctx, order, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserDB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.Pagination) uint64); ok {
		r1 = rf(ctx, order, pagination)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, models.Pagination) error); ok {
		r2 = rf(ctx, order, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - order string
//   - pagination modelsDB.Pagination
func (_e *MockUserRepository_Expecter) GetUsers(ctx interface{}, order interface{}, pagination interface{}) *MockUserRepository_GetUsers_Call {
	return &MockUserRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, order, pagination)}
}

func (_c *MockUserRepository_GetUsers_Call) Run(run func(ctx context.Context, order string, pagination models.Pagination)) *MockUserRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Pagination))
	})
	return _c
}

func (_c *MockUserRepository_GetUsers_Call) Return(_a0 []models.UserDB, _a1 uint64, _a2 error) *MockUserRepository_GetUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserRepository_GetUsers_Call) RunAndReturn(run func(context.Context, string, models.Pagination) ([]models.UserDB, uint64, error)) *MockUserRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, fields
func (_m *MockUserRepository) Update(ctx context.Context, id uuid.UUID, fields map[string]interface{}) (*models.UserDB, error) {
	ret := _m.Called(ctx, id, fields)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.UserDB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) (*models.UserDB, error)); ok {
		return rf(ctx, id, fields)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) *models.UserDB); ok {
		r0 = rf(ctx, id, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]interface{}) error); ok {
		r1 = rf(ctx, id, fields)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - fields map[string]interface{}
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, id interface{}, fields interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, fields)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, fields map[string]interface{})) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 *models.UserDB, _a1 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, map[string]interface{}) (*models.UserDB, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
