// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"
	config "wordsGo/internal/config"

	mock "github.com/stretchr/testify/mock"

	models "wordsGo/internal/models"

	uuid "github.com/google/uuid"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, email, password
func (_m *MockUserService) Authenticate(ctx context.Context, email string, password string) (*models.User, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockUserService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUserService_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *MockUserService_Authenticate_Call {
	return &MockUserService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *MockUserService_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *MockUserService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_Authenticate_Call) Return(_a0 *models.User, _a1 error) *MockUserService_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (*models.User, error)) *MockUserService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockUserService) Create(ctx context.Context, req models.CreateUserRequest) (*models.UserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateUserRequest) (*models.UserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateUserRequest) *models.UserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateUserRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.CreateUserRequest
func (_e *MockUserService_Expecter) Create(ctx interface{}, req interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockUserService_Create_Call) Run(run func(ctx context.Context, req models.CreateUserRequest)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateUserRequest))
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(_a0 *models.UserResponse, _a1 error) *MockUserService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(context.Context, models.CreateUserRequest) (*models.UserResponse, error)) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, requester, targetID
func (_m *MockUserService) Delete(ctx context.Context, requester *models.User, targetID uuid.UUID) error {
	ret := _m.Called(ctx, requester, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, uuid.UUID) error); ok {
		r0 = rf(ctx, requester, targetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - requester *models.User
//   - targetID uuid.UUID
func (_e *MockUserService_Expecter) Delete(ctx interface{}, requester interface{}, targetID interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, requester, targetID)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, requester *models.User, targetID uuid.UUID)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(_a0 error) *MockUserService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(context.Context, *models.User, uuid.UUID) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserService) GetUserByID(ctx context.Context, id uuid.UUID) (*models.UserResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.UserResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.UserResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(_a0 *models.UserResponse, _a1 error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.UserResponse, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx, limit, page, order
func (_m *MockUserService) GetUsers(ctx context.Context, limit uint64, page uint64, order string) (*models.ListOfUsersResponse, error) {
	ret := _m.Called(ctx, limit, page, order)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *models.ListOfUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, string) (*models.ListOfUsersResponse, error)); ok {
		return rf(ctx, limit, page, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, string) *models.ListOfUsersResponse); ok {
		r0 = rf(ctx, limit, page, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListOfUsersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, string) error); ok {
		r1 = rf(ctx, limit, page, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - page uint64
//   - order string
func (_e *MockUserService_Expecter) GetUsers(ctx interface{}, limit interface{}, page interface{}, order interface{}) *MockUserService_GetUsers_Call {
	return &MockUserService_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, limit, page, order)}
}

func (_c *MockUserService_GetUsers_Call) Run(run func(ctx context.Context, limit uint64, page uint64, order string)) *MockUserService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(string))
	})
	return _c
}

func (_c *MockUserService_GetUsers_Call) Return(_a0 *models.ListOfUsersResponse, _a1 error) *MockUserService_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUsers_Call) RunAndReturn(run func(context.Context, uint64, uint64, string) (*models.ListOfUsersResponse, error)) *MockUserService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockUserService) Login(ctx context.Context, req models.LoginRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.LoginRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.LoginRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.LoginRequest
func (_e *MockUserService_Expecter) Login(ctx interface{}, req interface{}) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, req models.LoginRequest)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.LoginRequest))
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(_a0 string, _a1 error) *MockUserService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(context.Context, models.LoginRequest) (string, error)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// SyncAdmin provides a mock function with given fields: ctx, adminCfg
func (_m *MockUserService) SyncAdmin(ctx context.Context, adminCfg config.Admin) error {
	ret := _m.Called(ctx, adminCfg)

	if len(ret) == 0 {
		panic("no return value specified for SyncAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, config.Admin) error); ok {
		r0 = rf(ctx, adminCfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_SyncAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAdmin'
type MockUserService_SyncAdmin_Call struct {
	*mock.Call
}

// SyncAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - adminCfg config.Admin
func (_e *MockUserService_Expecter) SyncAdmin(ctx interface{}, adminCfg interface{}) *MockUserService_SyncAdmin_Call {
	return &MockUserService_SyncAdmin_Call{Call: _e.mock.On("SyncAdmin", ctx, adminCfg)}
}

func (_c *MockUserService_SyncAdmin_Call) Run(run func(ctx context.Context, adminCfg config.Admin)) *MockUserService_SyncAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(config.Admin))
	})
	return _c
}

func (_c *MockUserService_SyncAdmin_Call) Return(_a0 error) *MockUserService_SyncAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_SyncAdmin_Call) RunAndReturn(run func(context.Context, config.Admin) error) *MockUserService_SyncAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockUserService) Update(ctx context.Context, id uuid.UUID, req models.UpdateUserRequest) (*models.UserResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.UpdateUserRequest) (*models.UserResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.UpdateUserRequest) *models.UserResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.UpdateUserRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req models.UpdateUserRequest
func (_e *MockUserService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockUserService_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, req models.UpdateUserRequest)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.UpdateUserRequest))
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(_a0 *models.UserResponse, _a1 error) *MockUserService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.UpdateUserRequest) (*models.UserResponse, error)) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
